version: "3.7"
services:
  jupyter:
    image: codecentric/from-jupyter-to-production-jupyter:latest
    ports:
      - 3000:3000
      - 8888:8888
      - 4141:4141
      - 7777:7777
    volumes:
      - type: bind
        source: ./notebooks
        target: /workshop/notebooks
      - workspace:/workshop/workspace
    links:
      - "mlflow:mlflow"
  mlflow:
    image: codecentric/from-jupyter-to-production-mlflow:latest
    ports:
      - 5001:5001
    volumes:
      - workspace:/ml_data/mlruns
volumes:
  workspace:
