version: '3.7'
services:
  jupyter:
    image: "ws_data_production"
    build: ../from-jupyter-to-production-image
    ports:
      - 8888:8888
      - 4141:4141
      - 5000:5000
      - 8080:8080
    volumes:
      - type: bind
        source: ./notebooks
        target: /workshop/notebooks