version: "3.7"
services:
  jupyter:
    image: codecentric/from-jupyter-to-production-baseimage:latest
    ports:
      - 8888:8888
      - 4141:4141
      - 5001:5001
      - 7777:7777
    volumes:
      - type: bind
        source: ./notebooks
        target: /workshop/notebooks
      - workspace:/workshop/workspace
volumes:
  workspace:
