version: "3.7"
services:
  jupyter:
    image: radtkem/from-jupyter-to-production-baseimage:latest
    ports:
      - 8888:8888
      - 4141:4141
      - 5000:5000
      - 7777:7777
    volumes:
      - type: bind
        source: ./notebooks
        target: /workshop/notebooks
      - workspace:/workshop/workspace
  airflow:
    image: radtkem/from-jupyter-to-production-airflow-image:latest
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./notebooks/airflow/dags
        target: /usr/local/airflow/dags
      - type: bind
        source: ./notebooks/airflow/exercise-dataset-airflow
        target: /exercise-dataset-airflow
      - workspace:/workshop/workspace
volumes:
  workspace: